### ISSUE TITLE
Use PostCSS for class creation and styling.

### ISSUE THREAD

**Issue by JustinBlake00** [Marmalade-ai/company-website#24]
Convert current classes to implement PostCSS as recommended by Gatsby.
- Install the Gatsby PostCSS plugin gatsby-plugin-postcss (https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/).
- More info on PostCSS (https://postcss.org/).

**Comment by jimtyhurst** [comment]
* Resolved by Pull Request #47.
* PostCSS was installed as part of Pull Request #47.
