### ISSUE TITLE
Upgrade to Gatsby 3.9.1

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#29]
* The website is currently configured for Gatsby 3.0.3.
* Let's upgrade to Gatsby 3.9.1 (and Gatsby CLI 3.9.0), so that we have the most current fixes, features, and documentation.

## Development dependency
Two issues need to be resolved before this one can be started:

* Issue #2 
* Issue #3 

because the theme is not compatible with `gatsby`  3.9.1. So the theme needs to be upgraded first, then we can upgrade Gatsby for the website.

**Comment by craigfisk** [comment]
Sounds good.

https://www.linkedin.com/in/craigfisk <https://about.me/craigfisk>
(650) 336-8770

**Comment by jimtyhurst** [comment]
Resolved by Pull Request #48.
