### ISSUE TITLE
Implement `niches` pages

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#55]
## Goal
* Quickly direct users to the specific benefits they should expect to receive from this site.
* This goes back to Doug Hunter's (plan reviewer from our Monday update list) suggestion that Lattice Semi's solution to enabling quick narrowing to the needs of who was using the site was through the menu going to specific needs.

## Proposed Changes
- [x] Replace "features benefits pricing" links in Header with "niches".
- [ ] "Niches" link in Header opens to dropdown menu with 4 choices that lead to brief pages for the benefits of Marmalade to each community of freelancers:
    - [ ] Digital Marketing
    - [ ] Machine Learning
    - [ ] UX Design
    - [ ] Other
- [ ] Use the ALT text also for captions for images.
    - [How to Add Markdown Image Captions in Gatsby](https://codeconcisely.com/posts/how-to-add-markdown-image-captions-in-gatsby/). 2021-07-21.
    - See the [gatsby-remark-images](https://www.gatsbyjs.com/plugins/gatsby-remark-images/) plugin for adding captions to images referenced in a Markdown file.

## Content
* See Marmalade > website > [Niches pages](https://docs.google.com/document/d/1CXoZ2ZO9mcolbg017W38fZoY0aSJUwlMaG-9HowqvY8/edit) for the images and text content.
    - Full-sentence tags are included for all images.

**Comment by jimtyhurst** [comment]
I pulled in some of the information from the `Description` field of Issue #94 into this issue and then closed that issue as a `duplicate` of this issue.

**Comment by craigfisk** [comment]
Yay !
