### ISSUE TITLE
Footer: `Code of Conduct`

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#7]
`Code of Conduct` (formerly `Terms and Conditions`) link should point to marmalade.ai content: Navigate to a separate `Code of Conduct` page on the company website. Content for this page is specified here:
Marmalade > website > Code of Conduct
https://docs.google.com/document/d/1P4m36xHiZEWLmv5l4QDWioBSOq_LclWrMC0DXKVt1Ss/edit?usp=sharing

Notes:

- This `Code of Content` applies to users of the networking application, but we want to make it available on the company website.
- There is no need for an `Accept` or `Decline` choice on this page. Other pages, e.g. the networking application's Register page will include a link to this company website page along with buttons or checkboxes, where the potential member can accept or reject the policy.

**Comment by JustinBlake00** [comment]
Fixed by pull request #19
