### ISSUE TITLE
Footer: `Privacy Policy`

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#8]
`Privacy Policy` link should point to marmalade.ai content: Click the link to navigate to a separate `Privacy Policy` page on the company website.

Design Notes:

- Content for that page can be copied and pasted from this text document:
    - Marmalade > website > [GDPR, CCPA, cookies, and data protection - misc.](https://docs.google.com/document/d/1K_1o3DgbqxoA6SiqUQB6CyQdHSkLYG6Z8U0D5Zle5ww/edit?usp=sharing)
- This page on the company website does not need to have `Accept` or `Decline` buttons or checkboxes. Those controls will appear as part of the registration process for the networking application. This page just has the content of the policies, which potential members can read outside of the registration process.

**Comment by JustinBlake00** [comment]
Fixed by pull request #20.
